import {
  MessagesSquare,
  
  Mic,
  FileText,
  Languages,
  Code2,
  FileUser,
  Mail,
  PenLine,
  Share2,
  SpellCheck,
  Sparkles,
  Receipt,
  ClipboardList,
  ScrollText,
  BarChart3,
  Briefcase,
  FileSignature,
  Presentation,
  type LucideIcon,
} from "lucide-react";

export type AiTool = {
  slug: string;
  to: string;
  title: string;
  hindi: string;
  description: string;
  icon: LucideIcon;
  accent: "saffron" | "green" | "royal";
  status: "live" | "soon";
  category?: "core" | "office";
};


export const AI_TOOLS: AiTool[] = [
  {
    slug: "chat",
    to: "/chat",
    title: "AI Chat",
    hindi: "एआई चैट",
    description: "Multilingual conversational AI powered by Gemini. Ask anything in Hindi or English.",
    icon: MessagesSquare,
    accent: "saffron",
    status: "live",
  },
  {
    slug: "voice",
    to: "/voice",
    title: "Voice Assistant",
    hindi: "आवाज़ सहायक",
    description: "Speak in any Indian language, get spoken answers back. Hands-free AI.",
    icon: Mic,
    accent: "green",
    status: "live",
  },
  {
    slug: "pdf",
    to: "/pdf",
    title: "PDF Chat",
    hindi: "पीडीएफ़ चैट",
    description: "Upload contracts, notes, research papers. Chat with any PDF in seconds.",
    icon: FileText,
    accent: "saffron",
    status: "live",
  },
  {
    slug: "translator",
    to: "/translator",
    title: "Indian Translator",
    hindi: "अनुवादक",
    description: "Translate across Hindi, Tamil, Bengali, Marathi, Telugu, Gujarati, and more.",
    icon: Languages,
    accent: "green",
    status: "live",
  },
  {
    slug: "coder",
    to: "/coder",
    title: "Coding Assistant",
    hindi: "कोडिंग सहायक",
    description: "Write, debug and explain code across 40+ languages with AI pair-programming.",
    icon: Code2,
    accent: "royal",
    status: "live",
  },
  {
    slug: "resume",
    to: "/resume",
    title: "Resume Builder",
    hindi: "रिज़्यूमे बिल्डर",
    description: "AI-crafted, ATS-friendly resumes tailored to Indian and global recruiters.",
    icon: FileUser,
    accent: "saffron",
    status: "live",
  },
  {
    slug: "email",
    to: "/email",
    title: "Email Writer",
    hindi: "ईमेल लेखक",
    description: "Professional emails in seconds — formal, casual, sales, apology templates.",
    icon: Mail,
    accent: "royal",
    status: "live",
  },
  {
    slug: "blog",
    to: "/blog-writer",
    title: "Blog Writer",
    hindi: "ब्लॉग लेखक",
    description: "Long-form SEO-ready blog posts with outlines, hooks and calls-to-action.",
    icon: PenLine,
    accent: "green",
    status: "live",
  },
  {
    slug: "social",
    to: "/social",
    title: "Social Media Posts",
    hindi: "सोशल पोस्ट",
    description: "Instagram, LinkedIn, X and WhatsApp captions in your brand voice.",
    icon: Share2,
    accent: "saffron",
    status: "live",
  },
  {
    slug: "grammar",
    to: "/grammar",
    title: "Grammar Checker",
    hindi: "व्याकरण जाँच",
    description: "Fix grammar, tone and clarity for English and Hindi text.",
    icon: SpellCheck,
    accent: "green",
    status: "live",
  },
  {
    slug: "summary",
    to: "/summarizer",
    title: "AI Summarizer",
    hindi: "सारांश",
    description: "Compress articles, meetings, research and books into crisp summaries.",
    icon: Sparkles,
    accent: "royal",
    status: "live",
  },
  {
    slug: "invoice",
    to: "/invoice",
    title: "Invoice Generator",
    hindi: "इनवॉइस जनरेटर",
    description: "Create GST-ready invoices in seconds. Download as PDF.",
    icon: Receipt,
    accent: "green",
    status: "live",
    category: "office",
  },
  {
    slug: "meeting-notes",
    to: "/meeting-notes",
    title: "Meeting Notes Generator",
    hindi: "मीटिंग नोट्स जनरेटर",
    description: "Turn meeting audio or transcripts into clean notes and action items.",
    icon: ClipboardList,
    accent: "royal",
    status: "live",
    category: "office",
  },
  {
    slug: "presentation",
    to: "/presentation",
    title: "Presentation Generator",
    hindi: "प्रेजेंटेशन जनरेटर",
    description: "Turn any topic into a ready slide outline. Export as PPTX.",
    icon: Presentation,
    accent: "royal",
    status: "live",
    category: "office",
  },
  {
    slug: "letter",
    to: "/letter",
    title: "Official Letter Writer",
    hindi: "आधिकारिक पत्र लेखक",
    description: "Draft leave applications, government letters and business letters instantly.",
    icon: ScrollText,
    accent: "saffron",
    status: "live",
    category: "office",
  },
  {
    slug: "data-analyzer",
    to: "/data-analyzer",
    title: "Data Analyzer",
    hindi: "डेटा एनालाइज़र",
    description: "Upload Excel or CSV files and get instant insights and charts.",
    icon: BarChart3,
    accent: "green",
    status: "live",
    category: "office",
  },
  {
    slug: "hr-assistant",
    to: "/hr-assistant",
    title: "HR Assistant",
    hindi: "एचआर सहायक",
    description: "Generate job descriptions and interview questions in seconds.",
    icon: Briefcase,
    accent: "royal",
    status: "live",
    category: "office",
  },
  {
    slug: "agreement",
    to: "/agreement",
    title: "Agreement Generator",
    hindi: "एग्रीमेंट जनरेटर",
    description: "Draft rent agreements, NDAs, offer letters and more.",
    icon: FileSignature,
    accent: "saffron",
    status: "live",
    category: "office",
  },
];

export const CORE_TOOLS = AI_TOOLS.filter((t) => t.category !== "office");
export const OFFICE_TOOLS = AI_TOOLS.filter((t) => t.category === "office");




export const accentClass: Record<AiTool["accent"], string> = {
  saffron: "from-[oklch(0.76_0.17_55)]/25 to-[oklch(0.68_0.2_30)]/10 text-[oklch(0.76_0.17_55)] ring-[oklch(0.76_0.17_55)]/30",
  green: "from-[oklch(0.66_0.16_155)]/25 to-[oklch(0.66_0.16_155)]/5 text-[oklch(0.72_0.16_155)] ring-[oklch(0.66_0.16_155)]/30",
  royal: "from-[oklch(0.62_0.19_260)]/25 to-[oklch(0.62_0.19_260)]/5 text-[oklch(0.72_0.15_260)] ring-[oklch(0.62_0.19_260)]/30",
};
