import type { FC } from "react";
import * as Text from "@/components/tools/text-tools";
import * as Calc from "@/components/tools/calculator-tools";
import * as Seo from "@/components/tools/seo-tools";
import * as Dev from "@/components/tools/developer-tools";
import * as Util from "@/components/tools/utility-tools";
import * as Img from "@/components/tools/image-tools";

export const TOOL_COMPONENTS: Record<string, FC> = {
  // text
  "word-counter": Text.WordCounter,
  "character-counter": Text.CharacterCounter,
  "case-converter": Text.CaseConverter,
  "remove-duplicate-lines": Text.RemoveDuplicateLines,
  "remove-empty-lines": Text.RemoveEmptyLines,
  "remove-extra-spaces": Text.RemoveExtraSpaces,
  "reverse-text": Text.ReverseText,
  "sort-text": Text.SortText,
  "text-compare": Text.TextCompare,
  "lorem-ipsum": Text.LoremIpsum,
  // calculators
  "age-calculator": Calc.AgeCalculator,
  "emi-calculator": Calc.EmiCalculator,
  "gst-calculator": Calc.GstCalculator,
  "gst-inclusive": Calc.GstInclusive,
  "gst-exclusive": Calc.GstExclusive,
  "sip-calculator": Calc.SipCalculator,
  "loan-calculator": Calc.LoanCalculator,
  "percentage-calculator": Calc.PercentageCalculator,
  "bmi-calculator": Calc.BmiCalculator,
  "bmr-calculator": Calc.BmrCalculator,
  "discount-calculator": Calc.DiscountCalculator,
  "profit-calculator": Calc.ProfitCalculator,
  "profit-margin": Calc.ProfitMargin,
  "date-difference": Calc.DateDifference,
  "time-calculator": Calc.TimeCalculator,
  "unit-converter": Calc.UnitConverter,
  "currency-converter": Calc.CurrencyConverter,
  "fuel-cost": Calc.FuelCost,
  "simple-interest": Calc.SimpleInterest,
  "compound-interest": Calc.CompoundInterest,
  // seo
  "meta-tag-generator": Seo.MetaTagGenerator,
  "sitemap-generator": Seo.SitemapGenerator,
  "robots-txt-generator": Seo.RobotsTxtGenerator,
  "og-generator": Seo.OgGenerator,
  "twitter-card-generator": Seo.TwitterCardGenerator,
  "slug-generator": Seo.SlugGenerator,
  "canonical-generator": Seo.CanonicalGenerator,
  "keyword-density": Seo.KeywordDensity,
  "schema-generator": Seo.SchemaGenerator,
  "sitemap-validator": Seo.SitemapValidator,
  // developer
  "json-formatter": Dev.JsonFormatter,
  "json-validator": Dev.JsonValidator,
  "json-viewer": Dev.JsonViewer,
  "html-formatter": Dev.HtmlFormatter,
  "css-minifier": Dev.CssMinifier,
  "js-minifier": Dev.JsMinifier,
  "sql-formatter": Dev.SqlFormatter,
  "xml-formatter": Dev.XmlFormatter,
  "url-encoder": Dev.UrlEncoder,
  "url-decoder": Dev.UrlDecoder,
  "base64-encoder": Dev.Base64Encoder,
  "base64-decoder": Dev.Base64Decoder,
  "uuid-generator": Dev.UuidGenerator,
  "md5-generator": Dev.Md5Generator,
  "sha256-generator": Dev.Sha256Generator,
  // utility
  "qr-code-generator": Util.QrCodeGenerator,
  "barcode-generator": Util.BarcodeGenerator,
  "password-generator": Util.PasswordGenerator,
  "password-strength": Util.PasswordStrength,
  "random-number": Util.RandomNumber,
  "color-picker": Util.ColorPicker,
  "hex-to-rgb": Util.HexToRgb,
  "rgb-to-hex": Util.RgbToHex,
  "digital-clock": Util.DigitalClock,
  "countdown-timer": Util.CountdownTimer,
  "stopwatch": Util.Stopwatch,
  "calendar": Util.CalendarTool,
  "notepad": Util.Notepad,
  "clipboard": Util.ClipboardTool,
  // image
  "image-compressor": Img.ImageCompressor,
  "resize-image": Img.ResizeImage,
  "crop-image": Img.CropImage,
  "jpg-to-png": Img.JpgToPng,
  "png-to-jpg": Img.PngToJpg,
  "webp-converter": Img.WebpConverter,
  "image-to-base64": Img.ImageToBase64,
  "base64-to-image": Img.Base64ToImage,
  "rotate-image": Img.RotateImage,
  "flip-image": Img.FlipImage,
};
