import { createFileRoute } from "@tanstack/react-router";
import { LegalShell } from "@/components/legal-shell";

const URL = "https://bharataisathi.com/ai-policy";
const TITLE = "AI Usage Policy — Bharat AI Sathi";
const DESC = "How Bharat AI Sathi uses artificial intelligence, what models power our tools, how outputs are generated, and what users should know before relying on AI-generated content.";

export const Route = createFileRoute("/ai-policy")({
  head: () => ({
    meta: [
      { title: TITLE },
      { name: "description", content: DESC },
      { property: "og:title", content: TITLE },
      { property: "og:description", content: DESC },
      { property: "og:url", content: URL },
      { property: "og:type", content: "article" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
    links: [{ rel: "canonical", href: URL }],
  }),
  component: AiPolicyPage,
});

function AiPolicyPage() {
  return (
    <LegalShell
      title="AI Usage Policy"
      subtitle="How Bharat AI Sathi builds, deploys and monitors AI features."
      updated="July 19, 2026"
    >
      <p>
        Bharat AI Sathi is an AI-powered productivity platform built for India. This policy explains
        how we use artificial intelligence across our tools, what data those models see, and the
        limits users should be aware of when they rely on AI-generated output.
      </p>

      <h2>1. Which AI models we use</h2>
      <p>
        Our AI features are powered by leading large language models accessed through secure API
        gateways, including Google Gemini for chat, translation, summarisation, code, resume,
        grammar, blog, email and social generation. We may switch or add providers over time to
        improve quality, latency or cost. When we do, we update this page.
      </p>

      <h2>2. What data is sent to AI providers</h2>
      <ul>
        <li>The prompt or content you submit (e.g. your chat message, PDF text, code snippet, image OCR text).</li>
        <li>Model configuration such as language, tone and temperature.</li>
        <li>Non-identifying request metadata required for abuse prevention.</li>
      </ul>
      <p>
        We do <strong>not</strong> attach your name, email, phone number or account ID to prompts
        sent to third-party AI providers. Do not paste passwords, Aadhaar/PAN numbers, bank
        credentials or any confidential information into any AI tool.
      </p>

      <h2>3. How outputs are generated</h2>
      <p>
        AI outputs are produced statistically. They can look confident even when wrong, may reflect
        biases in the training data, and can differ each time you run the same prompt. Always
        review AI output before publishing, submitting, filing or forwarding it — especially for
        legal, medical, financial, tax and government matters.
      </p>

      <h2>4. Human oversight</h2>
      <p>
        Every feature that surfaces AI-generated text on our public pages (blog, help articles,
        service explainers, government service summaries) is reviewed by the Bharat AI Sathi editorial
        team before publication. See our <a href="/editorial-policy">Editorial Policy</a> for details.
      </p>

      <h2>5. Prohibited uses</h2>
      <ul>
        <li>Generating content that defames, harasses, threatens or discriminates against any person or group.</li>
        <li>Producing sexual content involving minors, or non-consensual intimate content of any person.</li>
        <li>Creating malware, phishing pages, fake government notices, forged documents or fake IDs.</li>
        <li>Impersonating a real person, official, government body or brand.</li>
        <li>Automated scraping or bulk misuse of our AI endpoints outside our published plans.</li>
      </ul>

      <h2>6. Government services disclaimer</h2>
      <p>
        Bharat AI Sathi is <strong>not</strong> a government website and is not affiliated with any
        Ministry, Department or agency of the Government of India. AI explanations of government
        schemes, eligibility, documents and processes are provided for information only. Always
        verify with the official portal linked on each service page before filing.
      </p>

      <h2>7. Copyright and attribution</h2>
      <p>
        You own the prompts you write. Outputs generated by AI on our platform are yours to use
        subject to applicable law and the terms of the underlying model. When you use AI-generated
        text in journalism, research or public communication, please disclose that fact to your
        audience.
      </p>

      <h2>8. Reporting an issue</h2>
      <p>
        If you encounter unsafe, inaccurate or offensive AI output on Bharat AI Sathi, email us at
        {" "}<a href="mailto:support@bharataisathi.com">support@bharataisathi.com</a> with the
        prompt, screenshot and time. We investigate every report.
      </p>

      <h2>9. Changes to this policy</h2>
      <p>
        We update this AI Usage Policy whenever we add new AI features, switch providers or change
        how data flows. The "Last updated" date at the top always reflects the latest version.
      </p>
    </LegalShell>
  );
}
