import { createFileRoute } from "@tanstack/react-router";
import { LegalShell } from "@/components/legal-shell";

const TITLE = "Disclaimer — Bharat AI Sathi";
const DESCRIPTION = "Bharat AI Sathi is an informational AI assistance platform, not a government website. Please verify important information from official sources.";
const URL = "https://bharataisathi.com/disclaimer";
const UPDATED = "18 July 2026";

export const Route = createFileRoute("/disclaimer")({
  head: () => ({
    meta: [
      { title: TITLE },
      { name: "description", content: DESCRIPTION },
      { property: "og:title", content: TITLE },
      { property: "og:description", content: DESCRIPTION },
      { property: "og:type", content: "website" },
      { property: "og:url", content: URL },
      { name: "twitter:card", content: "summary_large_image" },
      { name: "twitter:title", content: TITLE },
      { name: "twitter:description", content: DESCRIPTION },
    ],
    links: [{ rel: "canonical", href: URL }],
  }),
  component: () => (
    <LegalShell title="Disclaimer" subtitle="Please read carefully before using our information." updated={UPDATED}>
      <div className="rounded-lg border border-[oklch(0.76_0.17_55)]/40 bg-[oklch(0.76_0.17_55)]/10 p-4 text-sm text-foreground">
        <strong>Important:</strong> Bharat AI Sathi is an independent, informational and AI-assistance platform. We are <strong>NOT a government website</strong> and are not affiliated with, endorsed by or connected to the Government of India, any State Government, ministry or department.
      </div>

      <h2>1. Nature of the Platform</h2>
      <p>
        Bharat AI Sathi provides AI-powered tools and consolidated guidance on Indian government services, schemes and forms. All content — including eligibility criteria, documents, fees, timelines and step-by-step guides — is provided for <strong>informational purposes only</strong>.
      </p>

      <h2>2. Not a government website</h2>
      <ul>
        <li>We do not issue, process, approve or reject any government application.</li>
        <li>We do not collect government fees.</li>
        <li>We do not represent any ministry, department or officer.</li>
        <li>Official application must be made on the respective government portal.</li>
      </ul>

      <h2>3. Information may change</h2>
      <p>
        Government schemes, eligibility, forms, documents and processes are updated frequently by the concerned authorities. Information on this Platform may become outdated between updates. <strong>Always verify important details on the official government website</strong> linked from each service page before acting.
      </p>

      <h2>4. AI-generated content</h2>
      <p>
        Outputs from AI features (chat, summariser, explainers, document generator, etc.) are generated by third-party AI models. They may contain errors, omissions, hallucinations or bias. Do not rely on AI-generated content for legal, medical, financial or life-critical decisions.
      </p>

      <h2>5. No professional advice</h2>
      <p>
        Nothing on the Platform constitutes legal, tax, financial, medical or professional advice. Consult a qualified professional for your specific situation.
      </p>

      <h2>6. No liability for decisions</h2>
      <p>
        Bharat AI Sathi, its team and its partners are <strong>not responsible</strong> for any loss, damage or consequence arising from decisions made based on information or AI-generated guidance obtained through the Platform.
      </p>

      <h2>7. External links</h2>
      <p>
        The Platform links to government and third-party websites for your convenience. We do not control and are not responsible for their content or availability.
      </p>

      <h2>8. Beware of fraud</h2>
      <p>
        We will never ask you to pay us fees for government services or share OTPs and passwords. If someone claims to represent Bharat AI Sathi and asks for money or credentials — it is fraud. Report it to <a href="mailto:support@bharataisathi.com">support@bharataisathi.com</a>.
      </p>

      <h2>9. Contact</h2>
      <p>
        For corrections or takedown requests, email <a href="mailto:support@bharataisathi.com">support@bharataisathi.com</a>.
      </p>
    </LegalShell>
  ),
});
