import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Sparkles, Save, Download, Loader2, CheckCircle2, AlertTriangle, ExternalLink } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { Button } from "@/components/ui/button";
import { getForm, type GovForm } from "@/lib/gov-forms";
import { useGovProfile } from "@/lib/gov-profile";
import { useGovStore, uid } from "@/lib/gov-store";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import { downloadTextFile } from "@/lib/gov-download";

export const Route = createFileRoute("/gov/forms/$slug")({
  loader: ({ params }) => {
    const f = getForm(params.slug);
    if (!f) throw notFound();
    return { f };
  },
  head: ({ loaderData }) => {
    if (!loaderData) return { meta: [{ title: "Form not found" }, { name: "robots", content: "noindex" }] };
    const f = loaderData.f;
    return {
      meta: [
        { title: `${f.name} — AI Auto-Fill | Bharat AI Sathi` },
        { name: "description", content: `${f.description} Fill the ${f.name} form with AI auto-fill from your saved profile.` },
      ],
    };
  },
  notFoundComponent: () => <div className="p-10 text-center">Form not found. <Link to="/gov/forms" className="text-primary">Back</Link></div>,
  errorComponent: ({ error }) => <div className="p-10 text-center text-sm">Error: {error.message}</div>,
  component: FormFiller,
});

type Draft = { values: Record<string, string>; savedAt: number };

function FormFiller() {
  const { f } = Route.useLoaderData() as { f: GovForm };
  const [profile] = useGovProfile();
  const [draft, setDraft] = useGovStore<Draft | null>(`draft:${f.slug}`, null);
  const [values, setValues] = useState<Record<string, string>>({});
  const [suggested, setSuggested] = useState<Set<string>>(new Set());
  const [errors, setErrors] = useState<Record<string, string>>({});

  // Hydrate: draft > auto-fill from profile > empty
  useEffect(() => {
    if (draft?.values) {
      setValues(draft.values);
    } else {
      const seed: Record<string, string> = {};
      const suggestedKeys = new Set<string>();
      for (const field of f.fields) {
        if (field.profileKey) {
          const v = String(profile[field.profileKey] ?? "");
          if (v) { seed[field.key] = v; suggestedKeys.add(field.key); }
        }
      }
      setValues(seed);
      setSuggested(suggestedKeys);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [f.slug]);

  const progress = useMemo(() => {
    const required = f.fields.filter((x) => x.required);
    if (required.length === 0) return 100;
    const done = required.filter((x) => (values[x.key] ?? "").trim().length > 0).length;
    return Math.round((done / required.length) * 100);
  }, [values, f.fields]);

  const setV = (key: string, v: string) => {
    setValues((cur) => ({ ...cur, [key]: v }));
    setSuggested((s) => { const n = new Set(s); n.delete(key); return n; });
  };

  const autoFillAll = () => {
    const next = { ...values };
    const sug = new Set(suggested);
    let count = 0;
    for (const field of f.fields) {
      if (field.profileKey && !next[field.key]) {
        const v = String(profile[field.profileKey] ?? "");
        if (v) { next[field.key] = v; sug.add(field.key); count++; }
      }
    }
    setValues(next); setSuggested(sug);
    toast.success(count > 0 ? `Auto-filled ${count} field${count > 1 ? "s" : ""}` : "Nothing new to auto-fill — try updating your profile.");
  };

  const saveDraft = () => {
    setDraft({ values, savedAt: Date.now() });
    toast.success("Draft saved locally");
  };

  const validate = (): boolean => {
    const errs: Record<string, string> = {};
    for (const field of f.fields) {
      const v = (values[field.key] ?? "").trim();
      if (field.required && !v) errs[field.key] = "Required";
      else if (v && field.pattern && !new RegExp(field.pattern).test(v)) errs[field.key] = "Invalid format";
      else if (v && field.maxLength && v.length > field.maxLength) errs[field.key] = `Max ${field.maxLength} chars`;
    }
    setErrors(errs);
    if (Object.keys(errs).length) toast.error(`${Object.keys(errs).length} field(s) need attention`);
    return Object.keys(errs).length === 0;
  };

  const downloadFilled = () => {
    if (!validate()) return;
    const body = [
      `${f.name} (${f.hindi})`,
      `${f.authority}${f.official ? ` — ${f.official}` : ""}`,
      "".padEnd(60, "="),
      "",
      ...f.fields.map((x) => `${x.label}: ${values[x.key] ?? ""}`),
      "",
      `Generated by Bharat AI Sathi on ${new Date().toLocaleString("en-IN")}`,
    ].join("\n");
    downloadTextFile(`${f.slug}-${Date.now()}.txt`, body, {
      id: uid("dl"),
      name: `${f.name} (Filled)`,
      kind: "Form",
      category: f.category,
      createdAt: Date.now(),
    });
    toast.success("Downloaded. Also saved to Download Center.");
  };

  return (
    <div className="min-h-screen">
      <SiteHeader />
      <section className="mx-auto max-w-4xl px-4 py-8 sm:px-6">
        <Link to="/gov/forms" className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-primary">
          <ArrowLeft className="h-3.5 w-3.5" /> All forms
        </Link>
        <div className="mt-3 flex flex-wrap items-start justify-between gap-3">
          <div>
            <h1 className="font-display text-2xl font-bold sm:text-3xl">{f.name}</h1>
            <p className="text-sm text-primary">{f.hindi}</p>
            <p className="mt-1 text-xs text-muted-foreground">{f.authority} · <span className="uppercase">{f.category}</span></p>
          </div>
          {f.official && (
            <a href={f.official} target="_blank" rel="noreferrer noopener"
              className="inline-flex items-center gap-1 rounded-full border border-border/60 px-3 py-1.5 text-xs text-muted-foreground hover:border-primary/40 hover:text-primary">
              Official site <ExternalLink className="h-3 w-3" />
            </a>
          )}
        </div>
        <p className="mt-3 text-sm text-muted-foreground">{f.description}</p>

        <div className="mt-6 rounded-2xl border border-border/60 bg-card/40 p-4 sm:p-5">
          <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
            <div className="flex items-center gap-3">
              <div className="h-2 w-40 overflow-hidden rounded-full bg-muted">
                <div className="h-full bg-primary transition-all" style={{ width: `${progress}%` }} />
              </div>
              <span className="text-xs text-muted-foreground">{progress}% complete</span>
            </div>
            <div className="flex flex-wrap gap-2">
              <Button size="sm" variant="outline" onClick={autoFillAll}><Sparkles className="mr-1 h-3.5 w-3.5" /> AI Auto-Fill</Button>
              <Button size="sm" variant="outline" onClick={saveDraft}><Save className="mr-1 h-3.5 w-3.5" /> Save Draft</Button>
              <Button size="sm" onClick={downloadFilled}><Download className="mr-1 h-3.5 w-3.5" /> Download</Button>
            </div>
          </div>

          {draft && (
            <div className="mb-3 flex items-center gap-2 rounded-lg border border-primary/30 bg-primary/5 px-3 py-2 text-xs text-primary">
              <CheckCircle2 className="h-3.5 w-3.5" /> Draft auto-saved · {new Date(draft.savedAt).toLocaleString("en-IN")}
            </div>
          )}

          <div className="grid gap-4 sm:grid-cols-2">
            {f.fields.map((field) => {
              const err = errors[field.key];
              const isSuggested = suggested.has(field.key);
              return (
                <div key={field.key} className={field.type === "textarea" ? "sm:col-span-2" : ""}>
                  <label className="mb-1 flex items-center gap-2 text-xs font-semibold">
                    {field.label}{field.required && <span className="text-red-500">*</span>}
                    {isSuggested && <span className="rounded-full bg-primary/15 px-1.5 py-0.5 text-[9px] font-medium uppercase tracking-wider text-primary">AI suggested</span>}
                  </label>
                  {field.type === "textarea" ? (
                    <textarea value={values[field.key] ?? ""} onChange={(e) => setV(field.key, e.target.value)}
                      rows={3}
                      className={cn("w-full rounded-lg border bg-background/60 px-3 py-2 text-sm outline-none focus:border-primary/60",
                        err ? "border-red-500/60" : isSuggested ? "border-primary/50" : "border-border/60")} />
                  ) : field.type === "select" ? (
                    <select value={values[field.key] ?? ""} onChange={(e) => setV(field.key, e.target.value)}
                      className={cn("w-full rounded-lg border bg-background/60 px-3 py-2 text-sm outline-none focus:border-primary/60",
                        err ? "border-red-500/60" : isSuggested ? "border-primary/50" : "border-border/60")}>
                      <option value="">Select…</option>
                      {field.options?.map((o) => <option key={o} value={o}>{o}</option>)}
                    </select>
                  ) : (
                    <input type={field.type} value={values[field.key] ?? ""} onChange={(e) => setV(field.key, e.target.value)}
                      maxLength={field.maxLength}
                      className={cn("w-full rounded-lg border bg-background/60 px-3 py-2 text-sm outline-none focus:border-primary/60",
                        err ? "border-red-500/60" : isSuggested ? "border-primary/50" : "border-border/60")} />
                  )}
                  {field.hint && !err && <p className="mt-1 text-[11px] text-muted-foreground">{field.hint}</p>}
                  {err && <p className="mt-1 flex items-center gap-1 text-[11px] text-red-500"><AlertTriangle className="h-3 w-3" /> {err}</p>}
                </div>
              );
            })}
          </div>
        </div>

        <p className="mt-4 text-[11px] text-muted-foreground">
          Data stays on your device — nothing is uploaded. Always verify values before submitting on the official portal.
        </p>
      </section>
      <SiteFooter />
    </div>
  );
}
