/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as TranslatorRouteImport } from './routes/translator'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SummarizerRouteImport } from './routes/summarizer'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as PmayRouteImport } from './routes/pmay'
import { Route as PdfRouteImport } from './routes/pdf'
import { Route as MeetingNotesRouteImport } from './routes/meeting-notes'
import { Route as LetterRouteImport } from './routes/letter'
import { Route as InvoiceRouteImport } from './routes/invoice'
import { Route as HrAssistantRouteImport } from './routes/hr-assistant'
import { Route as GrammarRouteImport } from './routes/grammar'
import { Route as GovRouteImport } from './routes/gov'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EmailRouteImport } from './routes/email'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DataAnalyzerRouteImport } from './routes/data-analyzer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoderRouteImport } from './routes/coder'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BlogWriterRouteImport } from './routes/blog-writer'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiPolicyRouteImport } from './routes/ai-policy'
import { Route as AgreementRouteImport } from './routes/agreement'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as GovIndexRouteImport } from './routes/gov.index'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'
import { Route as GovTrackerRouteImport } from './routes/gov.tracker'
import { Route as GovSearchRouteImport } from './routes/gov.search'
import { Route as GovScanRouteImport } from './routes/gov.scan'
import { Route as GovRemindersRouteImport } from './routes/gov.reminders'
import { Route as GovProfileRouteImport } from './routes/gov.profile'
import { Route as GovOcrRouteImport } from './routes/gov.ocr'
import { Route as GovFormsRouteImport } from './routes/gov.forms'
import { Route as GovEligibilityRouteImport } from './routes/gov.eligibility'
import { Route as GovDownloadsRouteImport } from './routes/gov.downloads'
import { Route as GovDocumentsRouteImport } from './routes/gov.documents'
import { Route as GovBookmarksRouteImport } from './routes/gov.bookmarks'
import { Route as GovAskRouteImport } from './routes/gov.ask'
import { Route as GovSlugRouteImport } from './routes/gov.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAiRouteImport } from './routes/api/ai'
import { Route as GovFormsIndexRouteImport } from './routes/gov.forms.index'
import { Route as GovDocumentsIndexRouteImport } from './routes/gov.documents.index'
import { Route as GovFormsSlugRouteImport } from './routes/gov.forms.$slug'
import { Route as GovDocumentsSlugRouteImport } from './routes/gov.documents.$slug'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslatorRoute = TranslatorRouteImport.update({
  id: '/translator',
  path: '/translator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SummarizerRoute = SummarizerRouteImport.update({
  id: '/summarizer',
  path: '/summarizer',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const PmayRoute = PmayRouteImport.update({
  id: '/pmay',
  path: '/pmay',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfRoute = PdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingNotesRoute = MeetingNotesRouteImport.update({
  id: '/meeting-notes',
  path: '/meeting-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LetterRoute = LetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceRoute = InvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const HrAssistantRoute = HrAssistantRouteImport.update({
  id: '/hr-assistant',
  path: '/hr-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarRoute = GrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const GovRoute = GovRouteImport.update({
  id: '/gov',
  path: '/gov',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DataAnalyzerRoute = DataAnalyzerRouteImport.update({
  id: '/data-analyzer',
  path: '/data-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoderRoute = CoderRouteImport.update({
  id: '/coder',
  path: '/coder',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWriterRoute = BlogWriterRouteImport.update({
  id: '/blog-writer',
  path: '/blog-writer',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPolicyRoute = AiPolicyRouteImport.update({
  id: '/ai-policy',
  path: '/ai-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementRoute = AgreementRouteImport.update({
  id: '/agreement',
  path: '/agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const GovIndexRoute = GovIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GovRoute,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ToolsRoute,
} as any)
const GovTrackerRoute = GovTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => GovRoute,
} as any)
const GovSearchRoute = GovSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => GovRoute,
} as any)
const GovScanRoute = GovScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => GovRoute,
} as any)
const GovRemindersRoute = GovRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => GovRoute,
} as any)
const GovProfileRoute = GovProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => GovRoute,
} as any)
const GovOcrRoute = GovOcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => GovRoute,
} as any)
const GovFormsRoute = GovFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => GovRoute,
} as any)
const GovEligibilityRoute = GovEligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => GovRoute,
} as any)
const GovDownloadsRoute = GovDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => GovRoute,
} as any)
const GovDocumentsRoute = GovDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => GovRoute,
} as any)
const GovBookmarksRoute = GovBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => GovRoute,
} as any)
const GovAskRoute = GovAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => GovRoute,
} as any)
const GovSlugRoute = GovSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GovRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const GovFormsIndexRoute = GovFormsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GovFormsRoute,
} as any)
const GovDocumentsIndexRoute = GovDocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GovDocumentsRoute,
} as any)
const GovFormsSlugRoute = GovFormsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GovFormsRoute,
} as any)
const GovDocumentsSlugRoute = GovDocumentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GovDocumentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agreement': typeof AgreementRoute
  '/ai-policy': typeof AiPolicyRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/blog-writer': typeof BlogWriterRoute
  '/chat': typeof ChatRoute
  '/coder': typeof CoderRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/data-analyzer': typeof DataAnalyzerRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/email': typeof EmailRoute
  '/faq': typeof FaqRoute
  '/gov': typeof GovRouteWithChildren
  '/grammar': typeof GrammarRoute
  '/hr-assistant': typeof HrAssistantRoute
  '/invoice': typeof InvoiceRoute
  '/letter': typeof LetterRoute
  '/meeting-notes': typeof MeetingNotesRoute
  '/pdf': typeof PdfRoute
  '/pmay': typeof PmayRoute
  '/presentation': typeof PresentationRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/summarizer': typeof SummarizerRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/translator': typeof TranslatorRoute
  '/voice': typeof VoiceRoute
  '/api/ai': typeof ApiAiRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/gov/$slug': typeof GovSlugRoute
  '/gov/ask': typeof GovAskRoute
  '/gov/bookmarks': typeof GovBookmarksRoute
  '/gov/documents': typeof GovDocumentsRouteWithChildren
  '/gov/downloads': typeof GovDownloadsRoute
  '/gov/eligibility': typeof GovEligibilityRoute
  '/gov/forms': typeof GovFormsRouteWithChildren
  '/gov/ocr': typeof GovOcrRoute
  '/gov/profile': typeof GovProfileRoute
  '/gov/reminders': typeof GovRemindersRoute
  '/gov/scan': typeof GovScanRoute
  '/gov/search': typeof GovSearchRoute
  '/gov/tracker': typeof GovTrackerRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/gov/': typeof GovIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/gov/documents/$slug': typeof GovDocumentsSlugRoute
  '/gov/forms/$slug': typeof GovFormsSlugRoute
  '/gov/documents/': typeof GovDocumentsIndexRoute
  '/gov/forms/': typeof GovFormsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agreement': typeof AgreementRoute
  '/ai-policy': typeof AiPolicyRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/blog-writer': typeof BlogWriterRoute
  '/chat': typeof ChatRoute
  '/coder': typeof CoderRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/data-analyzer': typeof DataAnalyzerRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/email': typeof EmailRoute
  '/faq': typeof FaqRoute
  '/grammar': typeof GrammarRoute
  '/hr-assistant': typeof HrAssistantRoute
  '/invoice': typeof InvoiceRoute
  '/letter': typeof LetterRoute
  '/meeting-notes': typeof MeetingNotesRoute
  '/pdf': typeof PdfRoute
  '/pmay': typeof PmayRoute
  '/presentation': typeof PresentationRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/summarizer': typeof SummarizerRoute
  '/terms': typeof TermsRoute
  '/translator': typeof TranslatorRoute
  '/voice': typeof VoiceRoute
  '/api/ai': typeof ApiAiRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/gov/$slug': typeof GovSlugRoute
  '/gov/ask': typeof GovAskRoute
  '/gov/bookmarks': typeof GovBookmarksRoute
  '/gov/downloads': typeof GovDownloadsRoute
  '/gov/eligibility': typeof GovEligibilityRoute
  '/gov/ocr': typeof GovOcrRoute
  '/gov/profile': typeof GovProfileRoute
  '/gov/reminders': typeof GovRemindersRoute
  '/gov/scan': typeof GovScanRoute
  '/gov/search': typeof GovSearchRoute
  '/gov/tracker': typeof GovTrackerRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/gov': typeof GovIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/gov/documents/$slug': typeof GovDocumentsSlugRoute
  '/gov/forms/$slug': typeof GovFormsSlugRoute
  '/gov/documents': typeof GovDocumentsIndexRoute
  '/gov/forms': typeof GovFormsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agreement': typeof AgreementRoute
  '/ai-policy': typeof AiPolicyRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/blog-writer': typeof BlogWriterRoute
  '/chat': typeof ChatRoute
  '/coder': typeof CoderRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/data-analyzer': typeof DataAnalyzerRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/email': typeof EmailRoute
  '/faq': typeof FaqRoute
  '/gov': typeof GovRouteWithChildren
  '/grammar': typeof GrammarRoute
  '/hr-assistant': typeof HrAssistantRoute
  '/invoice': typeof InvoiceRoute
  '/letter': typeof LetterRoute
  '/meeting-notes': typeof MeetingNotesRoute
  '/pdf': typeof PdfRoute
  '/pmay': typeof PmayRoute
  '/presentation': typeof PresentationRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/summarizer': typeof SummarizerRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/translator': typeof TranslatorRoute
  '/voice': typeof VoiceRoute
  '/api/ai': typeof ApiAiRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/gov/$slug': typeof GovSlugRoute
  '/gov/ask': typeof GovAskRoute
  '/gov/bookmarks': typeof GovBookmarksRoute
  '/gov/documents': typeof GovDocumentsRouteWithChildren
  '/gov/downloads': typeof GovDownloadsRoute
  '/gov/eligibility': typeof GovEligibilityRoute
  '/gov/forms': typeof GovFormsRouteWithChildren
  '/gov/ocr': typeof GovOcrRoute
  '/gov/profile': typeof GovProfileRoute
  '/gov/reminders': typeof GovRemindersRoute
  '/gov/scan': typeof GovScanRoute
  '/gov/search': typeof GovSearchRoute
  '/gov/tracker': typeof GovTrackerRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/gov/': typeof GovIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/gov/documents/$slug': typeof GovDocumentsSlugRoute
  '/gov/forms/$slug': typeof GovFormsSlugRoute
  '/gov/documents/': typeof GovDocumentsIndexRoute
  '/gov/forms/': typeof GovFormsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agreement'
    | '/ai-policy'
    | '/auth'
    | '/blog'
    | '/blog-writer'
    | '/chat'
    | '/coder'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/data-analyzer'
    | '/disclaimer'
    | '/editorial-policy'
    | '/email'
    | '/faq'
    | '/gov'
    | '/grammar'
    | '/hr-assistant'
    | '/invoice'
    | '/letter'
    | '/meeting-notes'
    | '/pdf'
    | '/pmay'
    | '/presentation'
    | '/pricing'
    | '/privacy'
    | '/resume'
    | '/sitemap.xml'
    | '/social'
    | '/summarizer'
    | '/terms'
    | '/tools'
    | '/translator'
    | '/voice'
    | '/api/ai'
    | '/api/chat'
    | '/api/transcribe'
    | '/blog/$slug'
    | '/gov/$slug'
    | '/gov/ask'
    | '/gov/bookmarks'
    | '/gov/documents'
    | '/gov/downloads'
    | '/gov/eligibility'
    | '/gov/forms'
    | '/gov/ocr'
    | '/gov/profile'
    | '/gov/reminders'
    | '/gov/scan'
    | '/gov/search'
    | '/gov/tracker'
    | '/tools/$slug'
    | '/gov/'
    | '/tools/'
    | '/gov/documents/$slug'
    | '/gov/forms/$slug'
    | '/gov/documents/'
    | '/gov/forms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/agreement'
    | '/ai-policy'
    | '/auth'
    | '/blog'
    | '/blog-writer'
    | '/chat'
    | '/coder'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/data-analyzer'
    | '/disclaimer'
    | '/editorial-policy'
    | '/email'
    | '/faq'
    | '/grammar'
    | '/hr-assistant'
    | '/invoice'
    | '/letter'
    | '/meeting-notes'
    | '/pdf'
    | '/pmay'
    | '/presentation'
    | '/pricing'
    | '/privacy'
    | '/resume'
    | '/sitemap.xml'
    | '/social'
    | '/summarizer'
    | '/terms'
    | '/translator'
    | '/voice'
    | '/api/ai'
    | '/api/chat'
    | '/api/transcribe'
    | '/blog/$slug'
    | '/gov/$slug'
    | '/gov/ask'
    | '/gov/bookmarks'
    | '/gov/downloads'
    | '/gov/eligibility'
    | '/gov/ocr'
    | '/gov/profile'
    | '/gov/reminders'
    | '/gov/scan'
    | '/gov/search'
    | '/gov/tracker'
    | '/tools/$slug'
    | '/gov'
    | '/tools'
    | '/gov/documents/$slug'
    | '/gov/forms/$slug'
    | '/gov/documents'
    | '/gov/forms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agreement'
    | '/ai-policy'
    | '/auth'
    | '/blog'
    | '/blog-writer'
    | '/chat'
    | '/coder'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/data-analyzer'
    | '/disclaimer'
    | '/editorial-policy'
    | '/email'
    | '/faq'
    | '/gov'
    | '/grammar'
    | '/hr-assistant'
    | '/invoice'
    | '/letter'
    | '/meeting-notes'
    | '/pdf'
    | '/pmay'
    | '/presentation'
    | '/pricing'
    | '/privacy'
    | '/resume'
    | '/sitemap.xml'
    | '/social'
    | '/summarizer'
    | '/terms'
    | '/tools'
    | '/translator'
    | '/voice'
    | '/api/ai'
    | '/api/chat'
    | '/api/transcribe'
    | '/blog/$slug'
    | '/gov/$slug'
    | '/gov/ask'
    | '/gov/bookmarks'
    | '/gov/documents'
    | '/gov/downloads'
    | '/gov/eligibility'
    | '/gov/forms'
    | '/gov/ocr'
    | '/gov/profile'
    | '/gov/reminders'
    | '/gov/scan'
    | '/gov/search'
    | '/gov/tracker'
    | '/tools/$slug'
    | '/gov/'
    | '/tools/'
    | '/gov/documents/$slug'
    | '/gov/forms/$slug'
    | '/gov/documents/'
    | '/gov/forms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AgreementRoute: typeof AgreementRoute
  AiPolicyRoute: typeof AiPolicyRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  BlogWriterRoute: typeof BlogWriterRoute
  ChatRoute: typeof ChatRoute
  CoderRoute: typeof CoderRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  DataAnalyzerRoute: typeof DataAnalyzerRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  EmailRoute: typeof EmailRoute
  FaqRoute: typeof FaqRoute
  GovRoute: typeof GovRouteWithChildren
  GrammarRoute: typeof GrammarRoute
  HrAssistantRoute: typeof HrAssistantRoute
  InvoiceRoute: typeof InvoiceRoute
  LetterRoute: typeof LetterRoute
  MeetingNotesRoute: typeof MeetingNotesRoute
  PdfRoute: typeof PdfRoute
  PmayRoute: typeof PmayRoute
  PresentationRoute: typeof PresentationRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResumeRoute: typeof ResumeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SocialRoute: typeof SocialRoute
  SummarizerRoute: typeof SummarizerRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  TranslatorRoute: typeof TranslatorRoute
  VoiceRoute: typeof VoiceRoute
  ApiAiRoute: typeof ApiAiRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translator': {
      id: '/translator'
      path: '/translator'
      fullPath: '/translator'
      preLoaderRoute: typeof TranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summarizer': {
      id: '/summarizer'
      path: '/summarizer'
      fullPath: '/summarizer'
      preLoaderRoute: typeof SummarizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pmay': {
      id: '/pmay'
      path: '/pmay'
      fullPath: '/pmay'
      preLoaderRoute: typeof PmayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf': {
      id: '/pdf'
      path: '/pdf'
      fullPath: '/pdf'
      preLoaderRoute: typeof PdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting-notes': {
      id: '/meeting-notes'
      path: '/meeting-notes'
      fullPath: '/meeting-notes'
      preLoaderRoute: typeof MeetingNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letter': {
      id: '/letter'
      path: '/letter'
      fullPath: '/letter'
      preLoaderRoute: typeof LetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice': {
      id: '/invoice'
      path: '/invoice'
      fullPath: '/invoice'
      preLoaderRoute: typeof InvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-assistant': {
      id: '/hr-assistant'
      path: '/hr-assistant'
      fullPath: '/hr-assistant'
      preLoaderRoute: typeof HrAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar': {
      id: '/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof GrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gov': {
      id: '/gov'
      path: '/gov'
      fullPath: '/gov'
      preLoaderRoute: typeof GovRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-analyzer': {
      id: '/data-analyzer'
      path: '/data-analyzer'
      fullPath: '/data-analyzer'
      preLoaderRoute: typeof DataAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coder': {
      id: '/coder'
      path: '/coder'
      fullPath: '/coder'
      preLoaderRoute: typeof CoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog-writer': {
      id: '/blog-writer'
      path: '/blog-writer'
      fullPath: '/blog-writer'
      preLoaderRoute: typeof BlogWriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-policy': {
      id: '/ai-policy'
      path: '/ai-policy'
      fullPath: '/ai-policy'
      preLoaderRoute: typeof AiPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreement': {
      id: '/agreement'
      path: '/agreement'
      fullPath: '/agreement'
      preLoaderRoute: typeof AgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/gov/': {
      id: '/gov/'
      path: '/'
      fullPath: '/gov/'
      preLoaderRoute: typeof GovIndexRouteImport
      parentRoute: typeof GovRoute
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/gov/tracker': {
      id: '/gov/tracker'
      path: '/tracker'
      fullPath: '/gov/tracker'
      preLoaderRoute: typeof GovTrackerRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/search': {
      id: '/gov/search'
      path: '/search'
      fullPath: '/gov/search'
      preLoaderRoute: typeof GovSearchRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/scan': {
      id: '/gov/scan'
      path: '/scan'
      fullPath: '/gov/scan'
      preLoaderRoute: typeof GovScanRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/reminders': {
      id: '/gov/reminders'
      path: '/reminders'
      fullPath: '/gov/reminders'
      preLoaderRoute: typeof GovRemindersRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/profile': {
      id: '/gov/profile'
      path: '/profile'
      fullPath: '/gov/profile'
      preLoaderRoute: typeof GovProfileRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/ocr': {
      id: '/gov/ocr'
      path: '/ocr'
      fullPath: '/gov/ocr'
      preLoaderRoute: typeof GovOcrRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/forms': {
      id: '/gov/forms'
      path: '/forms'
      fullPath: '/gov/forms'
      preLoaderRoute: typeof GovFormsRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/eligibility': {
      id: '/gov/eligibility'
      path: '/eligibility'
      fullPath: '/gov/eligibility'
      preLoaderRoute: typeof GovEligibilityRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/downloads': {
      id: '/gov/downloads'
      path: '/downloads'
      fullPath: '/gov/downloads'
      preLoaderRoute: typeof GovDownloadsRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/documents': {
      id: '/gov/documents'
      path: '/documents'
      fullPath: '/gov/documents'
      preLoaderRoute: typeof GovDocumentsRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/bookmarks': {
      id: '/gov/bookmarks'
      path: '/bookmarks'
      fullPath: '/gov/bookmarks'
      preLoaderRoute: typeof GovBookmarksRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/ask': {
      id: '/gov/ask'
      path: '/ask'
      fullPath: '/gov/ask'
      preLoaderRoute: typeof GovAskRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/$slug': {
      id: '/gov/$slug'
      path: '/$slug'
      fullPath: '/gov/$slug'
      preLoaderRoute: typeof GovSlugRouteImport
      parentRoute: typeof GovRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gov/forms/': {
      id: '/gov/forms/'
      path: '/'
      fullPath: '/gov/forms/'
      preLoaderRoute: typeof GovFormsIndexRouteImport
      parentRoute: typeof GovFormsRoute
    }
    '/gov/documents/': {
      id: '/gov/documents/'
      path: '/'
      fullPath: '/gov/documents/'
      preLoaderRoute: typeof GovDocumentsIndexRouteImport
      parentRoute: typeof GovDocumentsRoute
    }
    '/gov/forms/$slug': {
      id: '/gov/forms/$slug'
      path: '/$slug'
      fullPath: '/gov/forms/$slug'
      preLoaderRoute: typeof GovFormsSlugRouteImport
      parentRoute: typeof GovFormsRoute
    }
    '/gov/documents/$slug': {
      id: '/gov/documents/$slug'
      path: '/$slug'
      fullPath: '/gov/documents/$slug'
      preLoaderRoute: typeof GovDocumentsSlugRouteImport
      parentRoute: typeof GovDocumentsRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface GovDocumentsRouteChildren {
  GovDocumentsSlugRoute: typeof GovDocumentsSlugRoute
  GovDocumentsIndexRoute: typeof GovDocumentsIndexRoute
}

const GovDocumentsRouteChildren: GovDocumentsRouteChildren = {
  GovDocumentsSlugRoute: GovDocumentsSlugRoute,
  GovDocumentsIndexRoute: GovDocumentsIndexRoute,
}

const GovDocumentsRouteWithChildren = GovDocumentsRoute._addFileChildren(
  GovDocumentsRouteChildren,
)

interface GovFormsRouteChildren {
  GovFormsSlugRoute: typeof GovFormsSlugRoute
  GovFormsIndexRoute: typeof GovFormsIndexRoute
}

const GovFormsRouteChildren: GovFormsRouteChildren = {
  GovFormsSlugRoute: GovFormsSlugRoute,
  GovFormsIndexRoute: GovFormsIndexRoute,
}

const GovFormsRouteWithChildren = GovFormsRoute._addFileChildren(
  GovFormsRouteChildren,
)

interface GovRouteChildren {
  GovSlugRoute: typeof GovSlugRoute
  GovAskRoute: typeof GovAskRoute
  GovBookmarksRoute: typeof GovBookmarksRoute
  GovDocumentsRoute: typeof GovDocumentsRouteWithChildren
  GovDownloadsRoute: typeof GovDownloadsRoute
  GovEligibilityRoute: typeof GovEligibilityRoute
  GovFormsRoute: typeof GovFormsRouteWithChildren
  GovOcrRoute: typeof GovOcrRoute
  GovProfileRoute: typeof GovProfileRoute
  GovRemindersRoute: typeof GovRemindersRoute
  GovScanRoute: typeof GovScanRoute
  GovSearchRoute: typeof GovSearchRoute
  GovTrackerRoute: typeof GovTrackerRoute
  GovIndexRoute: typeof GovIndexRoute
}

const GovRouteChildren: GovRouteChildren = {
  GovSlugRoute: GovSlugRoute,
  GovAskRoute: GovAskRoute,
  GovBookmarksRoute: GovBookmarksRoute,
  GovDocumentsRoute: GovDocumentsRouteWithChildren,
  GovDownloadsRoute: GovDownloadsRoute,
  GovEligibilityRoute: GovEligibilityRoute,
  GovFormsRoute: GovFormsRouteWithChildren,
  GovOcrRoute: GovOcrRoute,
  GovProfileRoute: GovProfileRoute,
  GovRemindersRoute: GovRemindersRoute,
  GovScanRoute: GovScanRoute,
  GovSearchRoute: GovSearchRoute,
  GovTrackerRoute: GovTrackerRoute,
  GovIndexRoute: GovIndexRoute,
}

const GovRouteWithChildren = GovRoute._addFileChildren(GovRouteChildren)

interface ToolsRouteChildren {
  ToolsSlugRoute: typeof ToolsSlugRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsSlugRoute: ToolsSlugRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AgreementRoute: AgreementRoute,
  AiPolicyRoute: AiPolicyRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  BlogWriterRoute: BlogWriterRoute,
  ChatRoute: ChatRoute,
  CoderRoute: CoderRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  DataAnalyzerRoute: DataAnalyzerRoute,
  DisclaimerRoute: DisclaimerRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  EmailRoute: EmailRoute,
  FaqRoute: FaqRoute,
  GovRoute: GovRouteWithChildren,
  GrammarRoute: GrammarRoute,
  HrAssistantRoute: HrAssistantRoute,
  InvoiceRoute: InvoiceRoute,
  LetterRoute: LetterRoute,
  MeetingNotesRoute: MeetingNotesRoute,
  PdfRoute: PdfRoute,
  PmayRoute: PmayRoute,
  PresentationRoute: PresentationRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResumeRoute: ResumeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SocialRoute: SocialRoute,
  SummarizerRoute: SummarizerRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRouteWithChildren,
  TranslatorRoute: TranslatorRoute,
  VoiceRoute: VoiceRoute,
  ApiAiRoute: ApiAiRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
